name: CI

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  CI:
    name: CI
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: cosmowrap-hello-world

      - name: Setup Node.js
        uses: actions/setup-node@master
        with:
          node-version: '${{ steps.cosmowrap-hello-world.outputs.NVMRC }}'

      - name: Install dependencies
        run: yarn install --nonInteractive --frozen-lockfile --prefer-offline

      - name: Build
        run: yarn build
